services:
  opal-client:
    container_name: opal_client
    image: ${DOCKER_USERNAME}/opal-client:latest
    restart: always
    ports:
      - 3000:80
    networks:
      - opal-web-networks
networks:
  opal-web-networks:
    name: opal_web_networks
    external: true