on: 
    push: 
        branches: ['main']

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            - name: Build Image And Push
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
              run: docker compose build opal-client && docker compose push opal-client
    
    deploy-api:
        runs-on: arisa-server
        needs: build-image
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          API_URL: ${{secrets.API_URL}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Docker Login
              uses: docker/login-action@v3.1.0
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}
            
            - name: Stop Opal Client
              run: docker compose -f docker-compose.prod.yaml -p opal-client down opal-client --rmi all
              continue-on-error: true
          
            - name: Deploy Client
              run: docker compose -f docker-compose.prod.yaml -p opal-client up -d opal-client